language: php

php:
  - 7.4
  - 8.2

install:
  - composer i

script:
  - phpunit --coverage-clover=coverage.clover

#after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
